# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 019ba4f82d76b4be5649a62be4a00d8019909c703bf089999d820e9522b6bf86de3ec17352ae4038a8ed9ae033407ff1c99429b9ed6ca30cca18a9e12d8a9d1f

test:
  secret_key_base: 6ab6726ac0a223160380f42edbae8182ee919c0c785c631cb09aa0714180a40038d17a777dc2d25da81d10efb70b4148930d7eb94d1ab41b226a9f048df587e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
